### ISSUE TITLE
Check if a string is compressed

### ISSUE THREAD

**Issue by davidsoderberg** [nullpunkt/lz-string-php#4]
Hi,
How can I check if a string is already compressed?

**Comment by nullpunkt** [comment]
Hi,

you can't. But i think you should solve this issue outside of the (de)compression part. For example you can prefix your compressed string and/or directly send it to the interface/function which knows what to do.
So when your sender sends a compressed string to the receiver he should know if the message (string) is compressed or not -> and inform the receiver of its content (by using another url, function, etc. for each case)

Greetings
