### ISSUE TITLE
Compress & decompress UTF16

### ISSUE THREAD

**Issue by mattpass** [nullpunkt/lz-string-php#9]
The JS version of this lib has compressToUTF16 and decompressFromUTF16 available:

https://github.com/pieroxy/lz-string/blob/master/libs/lz-string.js#L47-L56

Would you be able to provide the same 1:1 implementation in PHP? Use case is that compress/decompress won't work with a big charset and Base64 is very bloated because it's mostly alphanumeric.

According to http://pieroxy.net/blog/pages/lz-string/index.html the UTF16 implementation only increases size by about 6% which is much better than the 166% bigger provided by Base64.

Specific use case is I have an code editor that needs to be able to save content of any type. Here's a file I use for testing, which of course fails using only compress/decompress:

```
FRENCH
Définir les permissions d'écriture (757 ou 775 selon votre système) sur les «sauvegardes», «lib ',' plugins ',' test 'et les dossiers' tmp '

FINNISH
Tämä osoittaa merkkejä joidenkin aksentti :ä, ö, å

RUSSIAN!
а б в г д е ё ж з и й к л м н о п р с т у ф х ц ч ш щ ъ ы ь э ю я

JAPANESE
馜簣襃 䰩かクェぢょ菣 ぽ饧饦褎姌 蟨姚獣禺蛣

PERSIAN
متن شگفت انگیز در اینجا

MATHS
Basic math sy㄀ mBals +-×º=()<>%
Algebra symbols x≜≈∑∏e
Geometry symbols ∡∟º´|||Δ
Statistical symbols P(A)f  (x)μσρzxχ 2
Logic symbols ^&+⊕⇒∀∃∴
Set theory symbols { }∩∪⊂∈Øℝ
Calculus & analysis symbols εiy'∫d/dx
Number symbols 01234567
Greek alphabet symbols αβγδεζηθ
Roman numerals XIVLCD
```

Hope you can help?

**Comment by nullpunkt** [comment]
Hi Matt, actually i'm busy but i put it this task on my todo list.

**Comment by mattpass** [comment]
Thanks @nullpunkt. If it makes any difference I may be able to fund this update if not too much. (Is for a open source code editor of my own that takes donations would be to happy to pass some donations on). Email me at info@icecoder.net if interested, else I'll have to wait. :-) No pressure, just an option.

**Comment by nullpunkt** [comment]
Hi @mattpass , check out current release (v1.2.0) and let me know if everything is working fine for you :-)

**Comment by mattpass** [comment]
Fantastic, thanks for looking at this @nullpunkt - I'll check it out and confirm if it works for me.
